In [41]:
import jax
import jax.numpy as jnp
import flax
import flax.linen as nn
import optax
from flax.training import train_state
from flax.training.train_state import TrainState


key = jax.random.PRNGKey(0)
q_key, x_key = jax.random.split(key)

x = jax.random.uniform(x_key, (1, 1,1,1))
class QNet(nn.Module):
    @nn.compact
    def __call__(self,x):
        x = jnp.transpose(x, (0, 3, 1, 2))  # NHWC to NCHW
        x = x/(225.0)
        x = nn.Conv(features=32, kernel_size=(8, 8), strides=(4, 4), use_bias=False)(x)
        x = nn.relu(x)
        x = nn.Conv(features=64, kernel_size=(4, 4), strides=(2, 2), use_bias=False)(x)
        x = nn.relu(x)
        x = nn.Conv(features=64, kernel_size=(3, 3), strides=(1, 1), use_bias=False)(x)
        x = nn.relu(x)
        x = x.reshape((x.shape[0], -1))  # Flatten
        x = nn.Dense(features=512, use_bias=False)(x)
        x = nn.relu(x)
        x = nn.Dense(features=4, use_bias=False)(x)  # Assuming 4 actions
        return x
class TrainState(TrainState):
        target_params: flax.core.FrozenDict

# def QNet_apply(params, x):
#     return QNet().apply({'params': params}, x)

params = QNet().init(q_key,x)
q_state = TrainState.create(
     apply_fn = QNet.apply,
     params = params,
     target_params = params,
     tx = optax.adam(learning_rate=0.0001),
#      tx_state = optax.adam(learning_rate=0.0001).init(params)
     )


q_state
    
    


TrainState(step=0, apply_fn=<function Module.apply at 0x7a75965ecf70>, params=FrozenDict({
    params: {
        Conv_0: {
            kernel: Array([[[[ 1.04711175e-01,  1.43368891e-03, -1.38142690e-01, ...,
                      -1.38462692e-01, -2.78626770e-01, -6.47766441e-02]],
            
                    [[-1.00971073e-01, -3.57258916e-02,  7.69592226e-02, ...,
                       6.06626347e-02, -3.66826169e-02, -4.28964803e-03]],
            
                    [[-1.89863637e-01,  8.05845559e-02,  1.86475202e-01, ...,
                       2.47723609e-02, -2.24789247e-01, -1.15498036e-01]],
            
                    ...,
            
                    [[ 9.87356454e-02, -5.43756336e-02,  4.14029211e-02, ...,
                      -1.12106325e-02, -6.85119182e-02,  1.22104891e-01]],
            
                    [[-2.15465911e-02, -2.06908926e-01, -4.58734892e-02, ...,
                      -9.20082629e-02,  1.93386097e-02,  1.61978483e-01]],
            
 

In [28]:
import jax
import jax.numpy as jnp

x = jnp.ones((1,1,1,4))
y = jnp.zeros((1,1,1,4))

#@jax.jit
def func(x, y):
    return x + y

z = func(x, y)

key = jax.random.PRNGKey(41)
keys, q_key = jax.random.split(key,2)
key, keys, q_key

model = QNet()
params = model.init(q_key, x)
params


FrozenDict({
    params: {
        Conv_0: {
            kernel: Array([[[[-4.22077850e-02, -2.54225284e-02, -6.64901882e-02, ...,
                      -1.29832014e-01,  7.98087642e-02,  7.20993280e-02]],
            
                    [[-3.28560956e-02, -6.95150197e-02,  4.07154560e-02, ...,
                       1.52028814e-01, -3.96683402e-02,  3.25144194e-02]],
            
                    [[-2.64752209e-02, -2.21771821e-01,  8.18167031e-02, ...,
                      -7.91133195e-02, -8.48743841e-02,  1.95348129e-01]],
            
                    ...,
            
                    [[-1.35919228e-01,  1.85411200e-02, -9.63977277e-02, ...,
                      -1.53303072e-01,  1.53771043e-01, -4.36498933e-02]],
            
                    [[ 2.34753460e-01,  4.68122959e-02,  2.89324559e-02, ...,
                      -9.47404057e-02, -8.51724821e-04,  2.91013904e-02]],
            
                    [[ 3.47693153e-02,  1.63757000e-02,  1.01740234e-01, ...,
 

In [18]:
import numpy as np
x = np.array((1,1,1,4))
z = np.array([[[[1,2,3,4]]]])
y= np.ndarray((1,1,1,4))
x,z,y

(array([1, 1, 1, 4]),
 array([[[[1, 2, 3, 4]]]]),
 array([[[[5.52019546e-320, 0.00000000e+000, 2.27930980e-316,
           2.26423487e-316]]]]))